# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\Account:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)css|images|js)/
            security: false

        main:
            custom_authenticators:
                - App\SecurityController

            form_login:
                login_path: login
                check_path: login
                provider: our_db_provider



    providers:
        our_db_provider:
            entity:
                class: App\Entity\Account
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }