index:
    path: /
    controller: App\Controller\DefaultController::index

afficheCreneau:
    path: /twigtest/{var}
    controller: App\Controller\DefaultController::afficheCreneau

afficheSemaine:
    path: /planningSemaine
    controller: App\Controller\DefaultController::afficheSemaine

newIntervenant_success:
    path:   /newintersuccess
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statics/success_intervenant.html.twig'
        maxAge: 86400
        sharedAge: 86400





