#
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#planningAnnuel:
#    path: /planningAnnuel/{user}
#    controller: App\Controller\DefaultController::planningAnnuel
#
#
#
newIntervenant_success:
  path:   /newintersuccess
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statics/success_intervenant.html.twig'
    maxAge: 86400
    sharedAge: 86400
newMatiere_success:
  path:   /newmatiersuccess
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'statics/success_matiere.html.twig'
    maxAge: 86400
    sharedAge: 86400


